
spring:
  application:
    name: words-service

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          fetch_size: 100
          batch_size: 100
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}?reWriteBatchedInserts=true&prepareThreshold=0
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 100MB

  cloud:
    loadbalancer:
      enabled: true

  batch:
    jdbc:
      initialize-schema: always
    job.enabled: false

  doc:
    api-docs:
      enabled: true
      path: /v3/api-docs
      x-logo: /documentation/lose-icon.png

  security:
    jwt:
      key:
        private: ${JWT_KEY}
      user:
        generator: ${JWT_USER}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE}

server:
  port: 8080

feign:
  client:
    config:
      default:
        loggerLevel: full