spring:
  application:
    name: words-service

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 100
        order_inserts: true
        generate_statistics: true  # Para ver estadísticas del batch insert en logs

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}?reWriteBatchedInserts=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false  # Desactivar auto-commit para mejor rendimiento en batch

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 100MB

  cloud:
    loadbalancer:
      enabled: true

  doc:
    api-docs:
      enabled: true
      path: /v3/api-docs
      x-logo: /documentation/lose-icon.png

  security:
    jwt:
      key:
        private: ${JWT_KEY}
      user:
        generator: ${JWT_USER}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE}

server:
  port: 8080

feign:
  client:
    config:
      default:
        loggerLevel: full